### PR TITLE
Added the Hebrew translation

### PR DESCRIPTION
**Pull request by yarons**
Also established a Transifex project: https://www.transifex.com/yaron/materialfbook/dashboard/

Thank you for this awesome project!

### CODE REVIEW

**Comment by ZeeRooo** [comment]
Thank you so much!!!

**Comment by ZeeRooo** [comment]
Please accept my request to join in the team in Transifex.

**Comment by yarons** [comment]
Lol Juan 😜 you asked to join the Hebrew team, I think it's better to create a team for your native language (unless it's Hebrew which in this case I'll approve you right away).

**Comment by ZeeRooo** [comment]
You are right xD
I never used this site, sorry

**Comment by yarons** [comment]
It's completely fine, what is you native language and user name in Transifex? I'll do the rest.

**Comment by ZeeRooo** [comment]
Im ZeeRooo in Transifex, my language is Spanish from Argentina (es_AR)

**Pull request merged**
